name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla-assistant:
    runs-on: "ubuntu-latest"
    steps:
      - name: "CLA Assistant"
        if: "(github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'"
        uses: contributor-assistant/github-action@v2.5.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PERSONAL_ACCESS_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        with:
          remote-organization-name: "semanticdatalayer"
          remote-repository-name: "sml-cla"
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/semanticdatalayer/SML/blob/main/CLA.md"
          branch: "main"
          allowlist: "dependabot[bot],greenkeeper[bot]"